# Generated by Django 4.2.13 on 2024-05-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile_api", "0003_scdhistory_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scdhistory",
            name="diagnose",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
